2x - y = 1
2x + 2y = 10

In [4]:
# this is a comment as it starts with #
#
# need numpy for matrices conventionally imported to be called np

import numpy as np


In [5]:
# declare matrix 
A = np.matrix('2 -1; 2 2')

#have a look at it
print(A)

[[ 2 -1]
 [ 2  2]]


In [6]:
#declare the second matrix
B = np.matrix('1; 10')
print(B)

[[ 1]
 [10]]


In [7]:
I = A.getI()
I

matrix([[ 0.33333333,  0.16666667],
        [-0.33333333,  0.33333333]])

In [8]:
answer = np.matmul(I,B)
print(answer)

[[2.]
 [3.]]


In [9]:
x = answer[0,0]
y = answer[1,0]

print(f'x = {x}')
print(f'y = {y}')

x = 2.0
y = 2.9999999999999996


In [15]:
# A= equations, B = solutions
def solveSimulEqn2by2(A, B):
    inverse = A.getI()
    answer = np.matmul(inverse, B)
    return answer[0, 0], answer[1, 0]


In [ ]:
# problems from workbook

In [16]:
x, y = solveSimulEqn2by2(np.matrix('2 -1; 2 2'), np.matrix('1; 10'))
print(f'x = {x}, y = {y}')

x = 2.0, y = 2.9999999999999996


In [17]:
x, y = x, y = solveSimulEqn2by2(np.matrix('2 3; 5 -2'), np.matrix('8; 1'))
print(f'x = {x}, y = {y}')

x = 1.0, y = 1.9999999999999998


In [19]:
x, y = solveSimulEqn2by2(np.matrix('3 5; 4 3'), np.matrix('7; 2'))
print(f'x = {x}, y = {y}')

x = -0.9999999999999999, y = 2.0


In [20]:
x, y = solveSimulEqn2by2(np.matrix('5 -1; 1 1'), np.matrix('15; -3'))
print(f'x = {x}, y = {y}')

x = 2.0, y = -5.0


In [21]:
x, y = solveSimulEqn2by2(np.matrix('3 -1; 2 5'), np.matrix('6; -13'))
print(f'x = {x}, y = {y}')

x = 1.0, y = -3.0


In [22]:
x, y = solveSimulEqn2by2(np.matrix('3 5; 1 -1'), np.matrix('1; -5'))
print(f'x = {x}, y = {y}')

x = -3.0, y = 2.0


In [23]:
x, y = solveSimulEqn2by2(np.matrix('2 -5; 3 2'), np.matrix('3; 14'))
print(f'x = {x}, y = {y}')

x = 4.0, y = 0.9999999999999999


In [24]:
x, y = solveSimulEqn2by2(np.matrix('2 3; 3 2'), np.matrix('6; -1'))
print(f'x = {x}, y = {y}')

x = -3.0, y = 3.9999999999999996


In [25]:
x, y = solveSimulEqn2by2(np.matrix('3 -1; 1 2'), np.matrix('18; -1'))
print(f'x = {x}, y = {y}')

x = 5.0, y = -2.9999999999999996


part 2

In [26]:
x, y = solveSimulEqn2by2(np.matrix('2 0; 3 4'), np.matrix('-8; 0'))
print(f'x = {x}, y = {y}')

x = -4.0, y = 3.0


In [32]:
x, y = solveSimulEqn2by2(np.matrix('3 2; 2 -5'), np.matrix('14; -16'))
print(f'x = {x}, y = {y}')

x = 1.9999999999999998, y = 4.0


In [33]:
x, y = solveSimulEqn2by2(np.matrix('-3 5; 2 3'), np.matrix('13; 4'))
print(f'x = {x}, y = {y}')

x = -1.0, y = 2.0


In [34]:
x, y = solveSimulEqn2by2(np.matrix('1 5; -2 3'), np.matrix('2; 9'))
print(f'x = {x}, y = {y}')

x = -2.9999999999999996, y = 1.0


In [35]:
x, y = solveSimulEqn2by2(np.matrix('4 3; -2 5'), np.matrix('-10; 18'))
print(f'x = {x}, y = {y}')

x = -4.0, y = 2.0


In [ ]:
x, y = solveSimulEqn2by2(np.matrix('2 5; -5 2'), np.matrix('-5; -31'))
print(f'x = {x}, y = {y}')