2x - y = 1
2x + 2y = 10

In [5]:
# this is a comment as it starts with #
#
# need numpy for matrices conventionally imported to be called np

import numpy as np


In [6]:
# declare matrix 
A = np.matrix('2 -1; 2 2')

#have a look at it
print(A)

[[ 2 -1]
 [ 2  2]]


In [7]:
#declare the second matrix
B = np.matrix('1; 10')
print(B)

[[ 1]
 [10]]


In [8]:
I = A.getI()
I

matrix([[ 0.33333333,  0.16666667],
        [-0.33333333,  0.33333333]])

In [10]:
answer = np.matmul(I,B)
print(answer)

[[2.]
 [3.]]


In [14]:
x = answer[0,0]
y = answer[1,0]

print(f'x = {x}')
print(f'y = {y}')

x = 2.0
y = 2.9999999999999996
