2x - y = 1
2x + 2y = 10

In [4]:
# this is a comment as it starts with #
#
# need numpy for matrices conventionally imported to be called np

import numpy as np


In [5]:
# declare matrix 
A = np.matrix('2 -1; 2 2')

#have a look at it
print(A)

[[ 2 -1]
 [ 2  2]]


In [6]:
#declare the second matrix
B = np.matrix('1; 10')
print(B)

[[ 1]
 [10]]


In [7]:
I = A.getI()
I

matrix([[ 0.33333333,  0.16666667],
        [-0.33333333,  0.33333333]])

In [8]:
answer = np.matmul(I,B)
print(answer)

[[2.]
 [3.]]


In [9]:
x = answer[0,0]
y = answer[1,0]

print(f'x = {x}')
print(f'y = {y}')

x = 2.0
y = 2.9999999999999996


In [14]:
# A= equations, B = solutions
def solveSimulEqn2by2(A, B):
    inverse = A.getI()
    answer = np.matmul(inverse, B)
    return answer[0, 0], answer[1, 0]

def solveSimulEqn3by3(A, B):
    inverse = A.getI()
    answer = np.matmul(inverse, B)
    return answer[0, 0], answer[1, 0], answer[3,0]


In [13]:
x,y = solveSimulEqn2by2(np.matrix('2 -1; 2 2'), np.matrix('1; 10'))
print(f'x = {x}, y = {y}')#

x = 2.0, y = 2.9999999999999996


In [ ]:
x,y,z = solveSimulEqn3by3()